name: Node.js CI with Yarn and Coveralls

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies using Yarn
        run: yarn install

      - name: Run tests with Yarn
        run: yarn test

      - name: Run coverage with Yarn
        run: yarn run coverage

      - name: Upload coverage to Coveralls
        run: cat ./coverage/lcov.info | yarn coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
